[package]
name = "epoch-store"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
epoch-proto = { workspace = true }
epoch-rocks = { workspace = true }
epoch-rpc = { workspace = true }
epoch-telemetry = { workspace = true }
rocksdb = { workspace = true }
thiserror = { workspace = true }
crc32c = { workspace = true }
tracing = { workspace = true }
prometheus = { workspace = true }
tokio = { workspace = true, features = ["sync", "rt"] }
bytes = { workspace = true }
async-trait = { workspace = true }

[target.'cfg(unix)'.dependencies]
libc = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "time"] }

[[bench]]
name = "sequential_write"
harness = false
