//! Control-plane gRPC contract (feature `grpc`): the PD-facing service that
//! gateways and DataNodes call ([`pd`]), plus the PD-internal replica raft
//! transport ([`raft`]). PD is the server; every other component is a client.
//! Messages use the epochIO vocabulary (Chunk / Shard / Extent), never
//! cubefs/MinIO terms (docs/design/00-overview.md §2; AGENTS §9.2).
//!
//! The stubs are generated by `tonic-prost-build` from `pd.proto` / `raft.proto`
//! at build time (see `build.rs`). The `PdControl` server is implemented in
//! epoch-pd; clients live in epoch-client. Extent operations travel on the
//! data-plane binary RPC (epoch-rpc), not here.
//!
//! Design: docs/design/01-pd.md §7 (control plane); §2 (raft); 06 §1

/// PD control-plane stubs generated from `pd.proto` (proto package `epoch.pd`).
pub mod pd {
    // Generated code: keep lints from failing the `-D warnings` clippy runs.
    #![allow(clippy::all, clippy::pedantic, clippy::nursery)]

    tonic::include_proto!("epoch.pd");
}

/// PD replica raft-transport stubs generated from `raft.proto` (proto package
/// `epoch.raft`). PD-internal (replica ↔ replica), not client-facing.
pub mod raft {
    // Generated code: keep lints from failing the `-D warnings` clippy runs.
    #![allow(clippy::all, clippy::pedantic, clippy::nursery)]

    tonic::include_proto!("epoch.raft");
}

/// MetaNode service stubs generated from `meta.proto` (proto package
/// `epoch.meta`): the PD-facing partition admin surface (CreateRaftGroup)
/// plus the gateway-facing flat-namespace metadata ops. The server is
/// implemented in epoch-meta; PD is the admin client, gateways the op clients.
pub mod meta {
    // Generated code: keep lints from failing the `-D warnings` clippy runs.
    #![allow(clippy::all, clippy::pedantic, clippy::nursery)]

    tonic::include_proto!("epoch.meta");
}

#[cfg(test)]
mod tests {
    use super::pd;

    // Compile-time proof that the service codegen produced both a server trait
    // and a client type (the surface epoch-pd / epoch-client implement next).
    #[allow(dead_code)]
    fn assert_service_stubs<T: pd::pd_control_server::PdControl>() -> core::marker::PhantomData<T> {
        let _client_ctor = pd::pd_control_client::PdControlClient::<tonic::transport::Channel>::new;
        core::marker::PhantomData
    }

    #[test]
    fn generated_messages_round_trip_fields() {
        let hb = pd::HeartbeatRequest {
            node_id: 7,
            disks: vec![pd::DiskStats {
                disk_id: 3,
                free: 100,
                used: 20,
                writable_extents: 5,
                broken: false,
            }],
        };
        assert_eq!(hb.node_id, 7);
        assert_eq!(hb.disks[0].writable_extents, 5);

        let view = pd::ChunkView {
            chunk_id: 42,
            code_mode: Some(pd::CodeMode {
                id: 1,
                data: 4,
                parity: 2,
                stripe_size: 1 << 20,
                blob_size: 32 << 20,
            }),
            status: pd::ChunkStatus::Writable as i32,
            shards: vec![pd::ShardView {
                shard_prefix: 0xDEAD_0000,
                epoch: 1,
                disk_id: 9,
                extent_id: vec![0u8; 16],
            }],
        };
        assert_eq!(view.status, pd::ChunkStatus::Writable as i32);
        assert_eq!(view.shards[0].extent_id.len(), 16);
    }

    #[test]
    fn partition_stat_total_bytes_round_trips_and_defaults_zero() {
        use prost::Message;

        // A fresh stat carries total_bytes end to end.
        let stat = pd::PartitionStat {
            partition_id: 5,
            leader_node_id: 2,
            applied_index: 100,
            inline_bytes: 4096,
            inline_count: 3,
            total_bytes: 8 << 30,
        };
        let bytes = stat.encode_to_vec();
        let decoded = pd::PartitionStat::decode(bytes.as_slice()).expect("decode");
        assert_eq!(decoded.total_bytes, 8 << 30);
        assert_eq!(decoded, stat);

        // A legacy encoding without field 6 decodes total_bytes = 0 (proto3
        // default): a stat encoded from only the first five fields.
        let legacy = pd::PartitionStat {
            partition_id: 5,
            leader_node_id: 2,
            applied_index: 100,
            inline_bytes: 4096,
            inline_count: 3,
            total_bytes: 0,
        };
        let legacy_bytes = legacy.encode_to_vec();
        // total_bytes = 0 is not serialized (proto3 skips default scalars), so
        // the wire form is byte-identical to a real legacy sender's output.
        let decoded = pd::PartitionStat::decode(legacy_bytes.as_slice()).expect("decode legacy");
        assert_eq!(decoded.total_bytes, 0);
    }
}
